### ISSUE TITLE
为什么只要加了"&dark_mode"，不管为true还是false都是黑暗模式啊

### ISSUE THREAD

**Issue by miaopan607** [cyrxdzj/luogu-card#1]
RT

**Comment by cyrxdzj** [comment]
以C++语言为例。
你以为的 `false`：
```cpp
bool dark_mode=false;
```
实际上的 `false`：
```cpp
string dark_mode="false";
```
事实上，这个参数是字符串类型的。如果你真的不想要黑暗模式，请勿指定此参数，或者：
```
https://luogu-card.vercel.app/practice?id=387836&dark_mode=&card_width=750&disable_cache=true
```

**Comment by miaopan607** [comment]
> 以C++语言为例。
> 你以为的 `false`：
> 
> ```c++
> bool dark_mode=false;
> ```
> 
> 实际上的 `false`：
> 
> ```c++
> string dark_mode="false";
> ```
> 
> 事实上，这个参数是字符串类型的。如果你真的不想要黑暗模式，请勿指定此参数，或者：
> 
> ```
> https://luogu-card.vercel.app/practice?id=387836&dark_mode=&card_width=750&disable_cache=true
> ```

额，看来这个与C++还是有很大的出入
话说以C++语言为例，不应该可以写成：
```cpp
string dark_mode = "false";
if (dark_mode == "true") ...;
else ...;
```
您的代码是 js 语言的，我不怎么看得懂……

**Comment by cyrxdzj** [comment]
JS是一个动态类型的语言，类型转换不好会出很多坑的……

**Comment by miaopan607** [comment]
时隔一年我退役之后的回复……

**Comment by cyrxdzj** [comment]
emmm因为我几乎忘了这里还有个issue没有被关闭，还好另一个人提交了另一个issue

**Comment by miaopan607** [comment]
额……
