### ISSUE TITLE
关于估值更新时间显示

### ISSUE THREAD

**Issue by y-kx-b** [cyrxdzj/luogu-card#2]
rt，希望估值卡片也能像练习情况那样加个更新时间，不过需要由用户自己填写。

**Comment by cyrxdzj** [comment]
收到。不过仅在咕值排名获取不到时才使用用户的填写内容。另外，用户也可以不填写。

**Comment by y-kx-b** [comment]
所以怎么填写呢qwq

time=···   还是什么的

**Comment by cyrxdzj** [comment]
是哒，就是time=（更新时间的伦敦时间距离1970年1月1日的秒数）。

**Comment by y-kx-b** [comment]
emm能不能就是精确到日就可以了，而且就按时间格式可以吗（我才不想每次更新都去转时间戳呢qwq）

**Comment by cyrxdzj** [comment]
啊哈，功能写完啦~具体请查看文档，设置时精确到毫秒，实际显示精确到秒。
