### ISSUE TITLE
似乎不能访问了

### ISSUE THREAD

**Issue by 0x3F-jerryCQ** [cyrxdzj/luogu-card#3]
rt

**Comment by cyrxdzj** [comment]
收到了。这似乎是因为vercel.app网挂了。
暂时找不到方法修复。

**Comment by WorldHim** [comment]
> 收到了。这似乎是因为vercel.app网挂了。 暂时找不到方法修复。

可以使用自己的域名，比如我的 `lg-card.worldhim.cf`

**Comment by 0x3F-jerryCQ** [comment]
谢谢！！！

从 Windows 版邮件发送

发件人: 邓子君Zijun Deng
发送时间: 2023年1月10日 14:09
收件人: cyrxdzj/luogu-card
抄送: 0x3F-jerryCQ; Author
主题: Re: [cyrxdzj/luogu-card] 似乎不能访问了 (Issue #3)

收到了。这似乎是因为vercel.app网挂了。
暂时找不到方法修复。

**Comment by 0x3F-jerryCQ** [comment]
谢谢！！！

从 Windows 版邮件发送

发件人: 邓子君Zijun Deng
发送时间: 2023年1月10日 14:09
收件人: cyrxdzj/luogu-card
抄送: 0x3F-jerryCQ; Author
主题: Re: [cyrxdzj/luogu-card] 似乎不能访问了 (Issue #3)

收到了。这似乎是因为vercel.app网挂了。
暂时找不到方法修复。

**Comment by 0x3F-jerryCQ** [comment]
谢谢！！！

 

发件人: ***@***.*** 代表 何嘉宸
发送时间: 2023年1月13日 13:40
收件人: cyrxdzj/luogu-card ***@***.***>
抄送: 0x3F-jerryCQ ***@***.***>; Author ***@***.***>
主题: Re: [cyrxdzj/luogu-card] 似乎不能访问了 (Issue #3)

 

收到了。这似乎是因为vercel.app网挂了。 暂时找不到方法修复。

可以使用自己的域名，比如我的 lg-card.worldhim.cf

**Comment by WorldHim** [comment]
把 issue close 吧

**Comment by 0x3F-jerryCQ** [comment]
Closed.
